language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
  - npm install -g npm@1.4.x
services:
  - redis-server
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
